### ISSUE TITLE
Feedback: Change Networking for Blob Storage to be Public but only During a Build

### ISSUE THREAD

**Issue by brmcmill** [jamasten/AzureImageBuilderAutomation#1]
Hey @jamasten -- had an idea with this unless it's too much overhead, but let's say for those customers who are using Custom Image Templates (CIT) and leverage Blob Storage to publicly host scripts.  As a security alternative unless/until this behavior ever changes for CIT, maybe during the automated build you could use a MI to change the Blob Storage Networking temporarily to public so the scripts are accessible.  Once the build completes, it turns it off and either disables it or sets to specific networks.  I guess you could capture what it was previous set to, and set it back.  Just something I thinking about that may offer up a better security approach.  Hope this helps.

**Comment by jamasten** [comment]
Hi @brmcmill. AIB works with service and private endpoints on the storage account that hosts the assets for the customizers. We all know the storage account in the staging resource group can’t be fixed. That’s a PG problem. I can work with you to create something custom for CIT since that service has more limitations but that would be a new solution / repo. Let’s chat next week about it. I’m happy to help!

**Comment by brmcmill** [comment]
Sounds good Jason.  Do you know if the PG has this kind of feedback on their radar yet?  Thanks!

**Comment by jamasten** [comment]
@brmcmill I haven't submitted anything.

**Comment by brmcmill** [comment]
Closing
